baseurl           = "/"
disableKinds      = "RSS"
languageCode      = "en-AU"
title             = "The Auction Queens"

[params]
  siteDescription = "Servicing the entire Mid North Coast"
  phone           = "0457 788 866"
  email           = "theauctionqueens@gmail.com"
  facebook        = "https://www.facebook.com/theauctionqueens"
  author          = ""
  twitterSite     = ""
  twitterCreator  = ""

[menu]
  [[menu.main]]
    name          = "Home"
    url           = "/"
    weight        = 1

  [[menu.main]]
    name          = "About"
    url           = "/about"
    weight        = 2

  [[menu.main]]
    name          = "Posts"
    url           = "/post"
    weight        = 3