baseurl           = "https://theauctionqueens.com.au/"
disableKinds      = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode      = "en-AU"
title             = "The Auction Queens"

[params]
  siteDescription = "Servicing the entire Mid North Coast"
  phone           = "0457 788 866"
  email           = "theauctionqueens@gmail.com"
  facebook        = "https://www.facebook.com/theauctionqueens"
  twitter         = ""
