backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    # - admin
    # - editor
  repo: lukebennett88/the-auction-queens # Path to your Github repository
  branch: master # Branch to update (master by default)

# publish_mode: editorial_workflow

media_folder: "/static/img/uploads" # Folder where user uploaded files should go
public_folder: "/img/uploads"

collections:
  - name: "auctions" # Post type identifier, used in routes. Must be unique.
    label: "Auctions" # Used in the UI, ie.: "New Post"
    label_singular: "Auction"
    folder: "/content/auctions/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}" # Template for filenames. {{year}}, {{month}}, and {{day}} pulls from the post's date field or save date. {{slug}} is a url-safe version of the post's title. Default is simply {{slug}}.
    extension: md
    format: toml-frontmatter
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      # - { label: "Draft", name: "draft", widget: "boolean", default: true }
